Repository phoebe-project/phoebe2, pull requests merged in 2024-06, with the labels that each got.

#883 Bump ndpolator version dependency to 1.2.
  phoebe/atmospheres/passbands.py
  pyproject.toml
Labels: enhancement

#884 macos-14 segfault bugfix (marching)
  phoebe/lib/Makefile
  phoebe/lib/bodies.h
  phoebe/lib/cvec.h
  phoebe/lib/gen_roche.h
  phoebe/lib/ld_models.h
  phoebe/lib/libphoebe.cpp
  phoebe/lib/misaligned_roche.h
  phoebe/lib/redistribution.h
  phoebe/lib/rot_star.h
  phoebe/lib/triang_marching.h
  phoebe/lib/utils.h
  setup.py
Labels: bug, urgent

#914 Adding back the definition of self.wl to passband load() function
  phoebe/atmospheres/passbands.py
Labels: bug
